# create environment: conda env create --file environment.yml
# activate environment: conda activate hperf_env
# remove environment: conda remove -n hperf_env --all
name: hperf_env
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
