# create environment: conda env create --file environment.yml
# activate environment: conda activate hperf
# remove environment: conda remove -n hperf --all
name: hperf
channels:
  - defaults
dependencies:
  - python=3.8
  - pandas
  - numpy
